import app

if __name__ == '__main__':
    app.semaphore_retry.delay(1, 2)
    app.semaphore_retry.delay(1, 4)
    app.semaphore_retry.delay(1, 6)
    app.semaphore_retry.delay(1, 8)
    app.semaphore_retry.delay(3, 10)
    app.semaphore_retry.delay(3, 12)
    app.semaphore_retry.delay(3, 14)
    app.semaphore_retry.delay(3, 16)
    app.semaphore_retry.delay(5, 18)
    app.semaphore_retry.delay(5, 20)
    app.semaphore_retry.delay(5, 22)
    app.semaphore_retry.delay(5, 24)
#    app.lock_block.delay(1, 2)
#    app.lock_block.delay(2, 3)
#    app.lock_args.delay(1, 2)
#    app.lock_args.delay(1, 3)
#    app.lock_args.delay(2, 3)
#    app.lock_args.delay(1, 3)
#    app.lock_identifier.delay(1, 2)
#    app.lock_path.delay(1, 2)
#    app.lock_no_block.delay(1, 2)
#    app.lock_no_block.delay(3, 4)
#    app.lock_retry.delay(3, 4)
#    app.lock_retry.delay(1, 2)
